### ISSUE TITLE
Uncaught ReferenceError: Prism is not defined in browser console after building Strapi with yarn build

### ISSUE THREAD

**Issue by tunjioye** [EdisonPeM/strapi-plugin-import-export-content#1]
For some reason, `prismjs` is not included in the build after installing this package.

**Here is a Screenshot of the Error**

![image](https://user-images.githubusercontent.com/9979650/115875775-7d796480-a43d-11eb-8675-d48e0b65b080.png)

**Comment by EdisonPeM** [comment]
Thanks for your issue, could you answer:

- What version of Strapí and Nodejs are you working on?
- Does this happen in all browsers?

**Comment by tunjioye** [comment]
> Thanks for your issue, could you answer:
> 
> * What version of Strapí and Nodejs are you working on?
> * Does this happen in all browsers?

Strapi v3.5.0
Node v12.17.0

Yes it happens in all browsers.

**Comment by EdisonPeM** [comment]
Hello, sorry for replying late.

I have not been able to replicate the issue, therefore I have not been able to work on it.

Try to use the latest versions of both strapi and this plugin, I will be working to complete it as soon as possible.

Thanks for your attention.
