### ISSUE TITLE
freezing at import

### ISSUE THREAD

**Issue by tadinski** [EdisonPeM/strapi-plugin-import-export-content#12]
when either pasting or selecting file to import, browser freezes, 
this issue occurs 6 out 10 times at least

**Comment by EdisonPeM** [comment]
hi, thanks for adding this issue

Do you know if this problem is related to the file size? maybe it's because of the content coloring, I don't know what other reason it could be.

**Comment by tadinski** [comment]
Unfortunately, I could not figure out where the issue was.
