### ISSUE TITLE
Export feature not working

### ISSUE THREAD

**Issue by alsino** [EdisonPeM/strapi-plugin-import-export-content#14]
Hi there,

amazing plugin, great work! 

The export feature does not to seem to work as expected at the moment. I am getting the following error: 

``export.items.error``

<img width="1186" alt="Bildschirmfoto 2021-05-30 um 10 35 19" src="https://user-images.githubusercontent.com/8008434/120097804-cd310700-c132-11eb-98cd-2fd5ad29375a.png">

**Comment by BenMcD0nald** [comment]
I think there's a fix waiting to go in that may resolve this: https://github.com/EdisonPeM/strapi-plugin-import-export-content/pull/8/files/c9a1b4881c3bf7afa072b9ba2e2eec3c33af01b2

**Comment by prof-jagpreet** [comment]
This error is still not resolved. Still getting the error.

![error1](https://user-images.githubusercontent.com/9291369/122060329-1cea2080-ce0b-11eb-9952-f41ffd69f479.png)

When we check console the we see the following error message.

![error2](https://user-images.githubusercontent.com/9291369/122060555-56229080-ce0b-11eb-993e-e6b4bb12ef66.png)


using MongoDB atlas as the database with Strapi latest version

Kindly check
