### ISSUE TITLE
Empty CSV fields can't be imported until "null" is written there

### ISSUE THREAD

**Issue by vkurlyan** [EdisonPeM/strapi-plugin-import-export-content#17]
If I export collection as CSV file which has empty fields (date, image, boolean fields), I might get such data in CSV:

```
title,image,date,some_boolean_field
Test title,,,
```

If I try to import this file back I see the message: "No items imported". It does not happen with JSON format.

Workaround: add "null" to an empty fields, then it works. Example:

```
title,image,date,some_boolean_field
Test title,null,null,null
```

**Comment by heyjaypray** [comment]
Another thing I wanted to add with this issue, is to make sure each column is the same data type specified in your Strapi models.  For instance, I had a content type that had a float, but the CSV columns were strings.  After specifying them as numbers Strapi accepted it!  I also made it so any cell that was empty said "null" as mentioned above.  Hope this helps anyone in the future!
