### ISSUE TITLE
Export feature not working on Latest Verison

### ISSUE THREAD

**Issue by prof-jagpreet** [EdisonPeM/strapi-plugin-import-export-content#18]
This error is still not resolved. Still getting the error.

![error1](https://user-images.githubusercontent.com/9291369/122060329-1cea2080-ce0b-11eb-9952-f41ffd69f479.png)

When we check console the we see the following error message.

![error2](https://user-images.githubusercontent.com/9291369/122060555-56229080-ce0b-11eb-993e-e6b4bb12ef66.png)

using MongoDB atlas as the database with Strapi latest version

Kindly check

**Comment by pdrakos** [comment]
same here.

**Comment by Barenstaden** [comment]
I managed to solve this by deleting "id" from the array "ignoreFileds" in services/exporter.js. Not entirely sure why it fails, but it seems to have something to do with id being an ObjectID (id: ObjectID("") in stead of id: String).

```
const ignoreFields = [
  "created_at",
  "created_by",
  "updated_at",
  "updated_by",
  "published_at",
];
```

**Comment by EdisonPeM** [comment]
@prof-jagpreet 

Try to test with the new version 4.0
