### ISSUE TITLE
Import and export destinations are showing empty

### ISSUE THREAD

**Issue by sreenivasbttv** [EdisonPeM/strapi-plugin-import-export-content#2]
Tested on Strapi 3.6.1 version

Content types are not showing for import and export destinations.

<img width="1433" alt="Screenshot 2021-05-01 at 1 23 47 AM" src="https://user-images.githubusercontent.com/2751681/116747893-3599a500-aa1c-11eb-9a56-6c78722c37f6.png">

while debugging file (admin/src/hooks/useContentTypes.js), noticed that after checking hasPermission for each content type getting empty array for **contentTypesWithPermissions**

Any solution? as an administrator, all permissions are updated properly.

**Comment by Hertak** [comment]
Did you find a solution?
