### ISSUE TITLE
Use Strapi Hash when importing password field

### ISSUE THREAD

**Issue by ardiansyaherwin** [EdisonPeM/strapi-plugin-import-export-content#22]
Hi Edison,

I've successfully import the data to users collection using your advice.
Now I'm facing another issue, which is to hash the password field before storing it to database.

I was thinking to override the controller, importItems, to alter the password field if any, then store the data.  I tried override the controller but it's failed.

Any idea where should I do the hash before send?

**Comment by EdisonPeM** [comment]
@ardiansyaherwin  you know if there is a strapi method for this type of field?, it could not make a different hash than the one used by strapi in its core
