### ISSUE TITLE
Can't import components and core_store

### ISSUE THREAD

**Issue by coderdix** [EdisonPeM/strapi-plugin-import-export-content#25]
Not sure if I'm missing something but when trying to import exports from a mongo csv/json export there wasn't a way to import my components or core_store files. 

Thanks!

**Comment by EdisonPeM** [comment]
Hi @coderdix, this plugin is only intended to import and export content defined by the developer, not the other types of content such as core_store, in the case of components they can be imported as objects when importing some content but not directly.
