### ISSUE TITLE
Strapi panel not showing

### ISSUE THREAD

**Issue by yangricardo** [EdisonPeM/strapi-plugin-import-export-content#28]
Hi, this is a very interesting plugin that i want to try to use.
However, the simple action of installing and build (`yarn build --clean`) made the administration panel not to be show anymore...
I am removing for now, but i'd like to use it in future

**Comment by EdisonPeM** [comment]
Hi @yangricardo
Give me the version of node and strapi you are working on to find a solution to this issue.
Thanks.

**Comment by yangricardo** [comment]
Hi! This issue was resolved on last update. Thanks.

**Comment by yangricardo** [comment]
Hi!
I tried the last update and it worked!
Please, would be nice to have a changelog document to keep track about this awesome plugin.
Thanks!
