### ISSUE TITLE
How to use?

### ISSUE THREAD

**Issue by cschweda** [EdisonPeM/strapi-plugin-import-export-content#3]
Do I install this into a pre-existing Strapi installation?

Does it automatically register itself?

I'm not sure how to use this.

**Comment by heyjaypray** [comment]
yarn build --clean
# or
npm run build -- --clean

**Comment by EdisonPeM** [comment]
Hello,

As @heyjaypray says, you can add this plugin to an existing project and run **build** clearing the cache.

Among the community there are more plugins that you can install to improve your project, here you can find some information about [strapi plugins here.](https://strapi.io/documentation/developer-docs/latest/development/plugin-customization.html)
