### ISSUE TITLE
Expand the list of CSV mime types

### ISSUE THREAD

**Issue by DaGhostman** [EdisonPeM/strapi-plugin-import-export-content#4]
Thanks for putting the effort in compiling some steps of the tutorials in a easy to use solution!

Unfortunately a couple of days back, after I had installed the plugin on a Strapi instance, I encountered an issue where uploading a CSV file is not recognized and gets rejected, after a little further investigation it seems that the file has mime type `text/plain` instead of `text/csv` .

I've did some investigation, but nothing I tried helped, and also stumbled upon some information that CSV file, might as well be with mime `application/vnd.ms-excel` because of some MS Excel reasons.. 

Will it be an interest to include additional types or if you could suggest any feasible workaround?

**Comment by EdisonPeM** [comment]
Thank you for your comments.

To deal with this problem, I added the **csv-excel** data type with the associated mimetype `application/vnd.ms-excel`, hope this can help solve this issue.

As for mime type `tex/plain` I will not support it as it can contain any format, or it is correct that your file has a mimetype `text/csv`.
